// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtTETH5lMTSrKpj_v3fbxv0BaaEfrsArk',
    appId: '1:915511624937:web:de502b8122659f46721c78',
    messagingSenderId: '915511624937',
    projectId: 'interview-task-48523',
    authDomain: 'interview-task-48523.firebaseapp.com',
    storageBucket: 'interview-task-48523.appspot.com',
    measurementId: 'G-7EFB4SC397',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1LgkLk2pvFcv412dSpvsfGQbdq_DfjwE',
    appId: '1:915511624937:android:bcc244bb1407a0c5721c78',
    messagingSenderId: '915511624937',
    projectId: 'interview-task-48523',
    storageBucket: 'interview-task-48523.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALgk2ksP_TA47cowF6-OvPe-uUPasJsKQ',
    appId: '1:915511624937:ios:d069653c4d2cdbf4721c78',
    messagingSenderId: '915511624937',
    projectId: 'interview-task-48523',
    storageBucket: 'interview-task-48523.appspot.com',
    iosBundleId: 'com.example.wingsAdvancedTasl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALgk2ksP_TA47cowF6-OvPe-uUPasJsKQ',
    appId: '1:915511624937:ios:8328d9f6eb32822d721c78',
    messagingSenderId: '915511624937',
    projectId: 'interview-task-48523',
    storageBucket: 'interview-task-48523.appspot.com',
    iosBundleId: 'com.example.wingsAdvancedTasl.RunnerTests',
  );
}
